INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('AF', 'Afghanistan', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('AL', 'Albania', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('DZ', 'Algeria', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('DS', 'American Samoa', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('AD', 'Andorra', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('AO', 'Angola', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('AI', 'Anguilla', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('AQ', 'Antarctica', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('AG', 'Antigua and Barbuda', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('AR', 'Argentina', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('AM', 'Armenia', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('AW', 'Aruba', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('AU', 'Australia', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('AT', 'Austria', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('AZ', 'Azerbaijan', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('BS', 'Bahamas', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('BH', 'Bahrain', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('BD', 'Bangladesh', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('BB', 'Barbados', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('BY', 'Belarus', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('BE', 'Belgium', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('BZ', 'Belize', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('BJ', 'Benin', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('BM', 'Bermuda', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('BT', 'Bhutan', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('BO', 'Bolivia', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('BA', 'Bosnia and Herzegovina', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('BW', 'Botswana', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('BV', 'Bouvet Island', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('BR', 'Brazil', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('IO', 'British Indian Ocean Territory', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('BN', 'Brunei Darussalam', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('BG', 'Bulgaria', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('BF', 'Burkina Faso', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('BI', 'Burundi', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('KH', 'Cambodia', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('CM', 'Cameroon', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('CA', 'Canada', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('CV', 'Cape Verde', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('KY', 'Cayman Islands', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('CF', 'Central African Republic', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('TD', 'Chad', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('CL', 'Chile', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('CN', 'China', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('CX', 'Christmas Island', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('CC', 'Cocos (Keeling) Islands', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('CO', 'Colombia', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('KM', 'Comoros', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('CG', 'Congo', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('CK', 'Cook Islands', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('CR', 'Costa Rica', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('HR', 'Croatia (Hrvatska)', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('CU', 'Cuba', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('CY', 'Cyprus', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('CZ', 'Czech Republic', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('DK', 'Denmark', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('DJ', 'Djibouti', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('DM', 'Dominica', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('DO', 'Dominican Republic', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('TP', 'East Timor', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('EC', 'Ecuador', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('EG', 'Egypt', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('SV', 'El Salvador', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('GQ', 'Equatorial Guinea', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('ER', 'Eritrea', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('EE', 'Estonia', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('ET', 'Ethiopia', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('FK', 'Falkland Islands (Malvinas)', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('FO', 'Faroe Islands', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('FJ', 'Fiji', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('FI', 'Finland', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('FR', 'France', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('FX', 'France, Metropolitan', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('GF', 'French Guiana', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('PF', 'French Polynesia', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('TF', 'French Southern Territories', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('GA', 'Gabon', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('GM', 'Gambia', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('GE', 'Georgia', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('DE', 'Germany', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('GH', 'Ghana', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('GI', 'Gibraltar', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('GK', 'Guernsey', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('GR', 'Greece', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('GL', 'Greenland', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('GD', 'Grenada', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('GP', 'Guadeloupe', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('GU', 'Guam', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('GT', 'Guatemala', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('GN', 'Guinea', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('GW', 'Guinea-Bissau', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('GY', 'Guyana', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('HT', 'Haiti', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('HM', 'Heard and Mc Donald Islands', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('HN', 'Honduras', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('HK', 'Hong Kong', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('HU', 'Hungary', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('IS', 'Iceland', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('IN', 'India', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('IM', 'Isle of Man', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('ID', 'Indonesia', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('IR', 'Iran (Islamic Republic of)', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('IQ', 'Iraq', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('IE', 'Ireland', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('IL', 'Israel', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('IT', 'Italy', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('CI', 'Ivory Coast', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('JE', 'Jersey', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('JM', 'Jamaica', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('JP', 'Japan', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('JO', 'Jordan', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('KZ', 'Kazakhstan', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('KE', 'Kenya', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('KI', 'Kiribati', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('KP', 'Korea, Democratic People''s Republic of', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('KR', 'Korea, Republic of', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('XK', 'Kosovo', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('KW', 'Kuwait', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('KG', 'Kyrgyzstan', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('LA', 'Lao People''s Democratic Republic', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('LV', 'Latvia', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('LB', 'Lebanon', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('LS', 'Lesotho', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('LR', 'Liberia', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('LY', 'Libyan Arab Jamahiriya', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('LI', 'Liechtenstein', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('LT', 'Lithuania', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('LU', 'Luxembourg', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('MO', 'Macau', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('MK', 'Macedonia', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('MG', 'Madagascar', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('MW', 'Malawi', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('MY', 'Malaysia', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('MV', 'Maldives', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('ML', 'Mali', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('MT', 'Malta', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('MH', 'Marshall Islands', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('MQ', 'Martinique', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('MR', 'Mauritania', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('MU', 'Mauritius', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('TY', 'Mayotte', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('MX', 'Mexico', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('FM', 'Micronesia, Federated States of', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('MD', 'Moldova, Republic of', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('MC', 'Monaco', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('MN', 'Mongolia', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('ME', 'Montenegro', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('MS', 'Montserrat', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('MA', 'Morocco', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('MZ', 'Mozambique', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('MM', 'Myanmar', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('NA', 'Namibia', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('NR', 'Nauru', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('NP', 'Nepal', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('NL', 'Netherlands', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('AN', 'Netherlands Antilles', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('NC', 'New Caledonia', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('NZ', 'New Zealand', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('NI', 'Nicaragua', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('NE', 'Niger', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('NG', 'Nigeria', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('NU', 'Niue', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('NF', 'Norfolk Island', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('MP', 'Northern Mariana Islands', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('NO', 'Norway', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('OM', 'Oman', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('PK', 'Pakistan', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('PW', 'Palau', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('PS', 'Palestine', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('PA', 'Panama', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('PG', 'Papua New Guinea', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('PY', 'Paraguay', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('PE', 'Peru', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('PH', 'Philippines', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('PN', 'Pitcairn', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('PL', 'Poland', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('PT', 'Portugal', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('PR', 'Puerto Rico', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('QA', 'Qatar', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('RE', 'Reunion', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('RO', 'Romania', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('RU', 'Russian Federation', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('RW', 'Rwanda', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('KN', 'Saint Kitts and Nevis', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('LC', 'Saint Lucia', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('VC', 'Saint Vincent and the Grenadines', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('WS', 'Samoa', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('SM', 'San Marino', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('ST', 'Sao Tome and Principe', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('SA', 'Saudi Arabia', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('SN', 'Senegal', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('RS', 'Serbia', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('SC', 'Seychelles', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('SL', 'Sierra Leone', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('SG', 'Singapore', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('SK', 'Slovakia', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('SI', 'Slovenia', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('SB', 'Solomon Islands', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('SO', 'Somalia', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('ZA', 'South Africa', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('GS', 'South Georgia South Sandwich Islands', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('ES', 'Spain', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('LK', 'Sri Lanka', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('SH', 'St. Helena', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('PM', 'St. Pierre and Miquelon', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('SD', 'Sudan', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('SR', 'Suriname', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('SJ', 'Svalbard and Jan Mayen Islands', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('SZ', 'Swaziland', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('SE', 'Sweden', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('CH', 'Switzerland', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('SY', 'Syrian Arab Republic', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('TW', 'Taiwan', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('TJ', 'Tajikistan', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('TZ', 'Tanzania, United Republic of', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('TH', 'Thailand', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('TG', 'Togo', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('TK', 'Tokelau', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('TO', 'Tonga', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('TT', 'Trinidad and Tobago', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('TN', 'Tunisia', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('TR', 'Turkey', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('TM', 'Turkmenistan', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('TC', 'Turks and Caicos Islands', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('TV', 'Tuvalu', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('UG', 'Uganda', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('UA', 'Ukraine', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('AE', 'United Arab Emirates', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('GB', 'United Kingdom', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('US', 'United States', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('UM', 'United States minor outlying islands', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('UY', 'Uruguay', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('UZ', 'Uzbekistan', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('VU', 'Vanuatu', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('VA', 'Vatican City State', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('VE', 'Venezuela', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('VN', 'Vietnam', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('VG', 'Virgin Islands (British)', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('VI', 'Virgin Islands (U.S.)', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('WF', 'Wallis and Futuna Islands', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('EH', 'Western Sahara', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('YE', 'Yemen', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('ZR', 'Zaire', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('ZM', 'Zambia', NOW());
INSERT INTO `countries`(`initals`, `name`, `created_at`) VALUES ('ZW', 'Zimbabwe', NOW());